### ISSUE TITLE
Code editor for zeebe-script-worker

### ISSUE THREAD

**Issue by phileas74** [sharedchains/camunda-code-editor#22]
Hi, I installed the script editor plugin under the impression that it also would work for Script tasks in Camunda Cloud workflows.
After I couldn't find the editor icon I realized that the Properties Panel in the screenshot shown in the README looks different from my panel. Only then I understood that this screenshot is probably showing a Camunda Platform workflow - and indeed, after creating a Script task in a new Camunda Platform workflow the editor showed up.

Would it be possible to make the editor also available for Script tasks in Camunda Cloud workflows?
Specifically for [zeebe-script-worker](https://github.com/camunda-community-hub/zeebe-script-worker), which expects the script to evaluate as a custom header field with the Key 'script'.

![code-editor-zeebe-script-runner](https://user-images.githubusercontent.com/19854070/156250220-d8c71420-3566-42af-b47f-a489d3cd5578.png)

Ideally the editor button (pen) should appear beside the Value field.

Note: Our company operates a customized Zeebe platform. As part of this the worker types also follow a custom naming convention. Long story short: In our setup the zeebe-script-worker's type is not 'script' but 'zeebe-script-runner'. Therefore, it should be possible to configure the task type for which the editor button (pen) appears (maybe also for which header field, e.g. 'script').

Best,
Phil

**Comment by Ichigo85** [comment]
Hello Phil,
as you said, our Code Editor works with the old bpmn properties panel. We are working on moving all our plugins to the new properties panel, in order to stay up to date with the next Camunda Modeler 5.0 version. Thank you for your suggestion, we'll try to follow it.

**Comment by phileas74** [comment]
Thanks Luca for your quick reply. Just another idea that came to my mind:
Since there is already a code editor available in Camunda Modeler, i.e. the editor to display the BPMN code (XML), wouldn't it be possible to leverage this code editor also for scripts (JS, Groovy, etc.), rather than providing a special editor just for that purpose?

I made a small screencast to demo the idea:

https://user-images.githubusercontent.com/19854070/156371512-c8282b0f-495c-4156-9c1f-73b677112268.mp4

1. User select a Script task and navigates to a 'script' field.
2. User clicks on the 'edit' button (e.g. pen) to open the editor.
3. Script opens in a new tab of the modeler's main section. -> in the screencast this step is faked by activating the already opened 'script.js' tab
4. User can edit and save the script as usual. Changed script is taken as new value for the related field.

Best,
Phil

**Comment by Ichigo85** [comment]
Well, I don't know! It's a good suggestion and I personally will think about it, but it depends on how much customization can be done in the new version of Camunda Modeler from inside the plugin code...
I will certainly study if that's possible, integrating a new wysiwyg script editor. 
I am sincerely not sure because I think every tab is like a 'separated' area.

**Comment by Ichigo85** [comment]
Hello @phileas74 ,
I currently developed the new version of our Code Editor for Camunda Modeler 5.0, it's not released yet but you can certainly try it if you like. Unfortunately I couldn't make much difference from the older code, anyway if you like you can fork our project and give it a try.

**Comment by phileas74** [comment]
Hi Luca, thanks for the update. Meanwhile, we implemented a small tool (Java Swing app) that allows to parse BPMN 2.0 model files and list service tasks of a specific type. You can open an external editor to edit scripts. Once you save and close the editor the BPMN model gets updated accordingly.

Here you see our tool (Zeebe Script Explorer) in action with an opened [Groovy Console](https://groovy-lang.org/groovyconsole.html) to edit a script:

![zse_aside_camunda_modeler](https://user-images.githubusercontent.com/19854070/177132688-283ca610-1b04-4578-b08e-3ed5ebf0fe82.png)

It would be nice to integrate the feature our tool offers in the Camunda Modeler, but for now it serves the purpose.

Best,
Phil

**Comment by Ichigo85** [comment]
Closing for now.
